spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true

  data:
    mongodb:
      host: localhost
      port: 27017

  devtools:
    restart:
      enabled: true # false 로 지정하면 개발자 도구에 의한 재시작을 비활성화 할 수 있음

# 웹 수준에서 발생하는 일을 로깅
# 예를 들면 HTTP 요청값이나 API routing 및 응답값 등등..
logging:
  level:
    web: DEBUG